export const FONTS: { label: string; css: string }[] = [
  { label: "Pretendard", css: "Pretendard" },
  { label: "Gmarket Sans", css: "GmarketSans" },
  { label: "Gmarket Sans Bold", css: "GmarketSansBold" },
  { label: "Seoul Namsan", css: "SeoulNamsan" },
  { label: "Tmon Monsori", css: "TmonMonsori" },
  { label: "BM Hanna Pro", css: "BMHANNAPro" },
  { label: "BM Dohyeon", css: "BMDOHYEON" },
  { label: "BM Euljiro", css: "BMEULJIRO" },
  { label: "BM Jua", css: "BMJUA" },
  { label: "BM Yeonsung", css: "BMYEONSUNG" },
  { label: "Cafe24 Ssurround", css: "Cafe24Ssurround" },
  { label: "Jalnan", css: "Jalnan" },
  { label: "Jeju Doldam", css: "JejuDoldam" },
  { label: "Dovemayo Gothic", css: "DovemayoGothic" },
  { label: "HS Santokki", css: "HSSantokki" },
];
