"""도우인 로그인 / 쿠키 자동관리 (Playwright).

문제: 최신 크롬/엣지는 App-Bound Encryption으로 쿠키 자동추출 차단(DPAPI 에러).
해결: 우리가 직접 Playwright 브라우저를 띄워 사용자가 1번 로그인 →
      그 브라우저의 쿠키를 우리가 저장. 확장프로그램·브라우저 종료 불필요.

흐름:
  1. login()  — 눈에 보이는 크로미엄으로 도우인 로그인 페이지 띄움.
                사용자가 QR/폰번호로 로그인. 로그인 감지되면 쿠키 저장.
  2. 저장 형식 2가지:
       - state.json    : Playwright storage_state (재로그인/재방문용)
       - cookies.txt   : Netscape 형식 (yt-dlp --cookiefile 용)
  3. is_logged_in() — 저장된 쿠키로 로그인 유효한지 확인.

쿠키 위치: WORKDIR/../auth/  (gitignore 대상, 민감정보)
"""
import json
import time
from pathlib import Path

from app.config import BACKEND_ROOT

AUTH_DIR = BACKEND_ROOT / "auth"
AUTH_DIR.mkdir(exist_ok=True)
STATE_PATH = AUTH_DIR / "douyin_state.json"
COOKIES_TXT = AUTH_DIR / "douyin_cookies.txt"

DOUYIN_URL = "https://www.douyin.com/"
# 로그인 성공 판정 쿠키 (실제 세션쿠키 — passport_csrf_token은 비로그인도 있어 제외)
LOGIN_COOKIE_HINTS = {"sessionid", "sessionid_ss", "sid_tt", "sid_guard"}


def _to_netscape(cookies: list, out_path: Path):
    """Playwright 쿠키 리스트 → Netscape cookies.txt (yt-dlp 호환)."""
    lines = ["# Netscape HTTP Cookie File", "# generated by douyin_auth", ""]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0)) if c.get("expires", -1) > 0 else 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _save(context):
    """현재 컨텍스트의 쿠키를 state.json + cookies.txt로 저장."""
    context.storage_state(path=str(STATE_PATH))
    cookies = context.cookies()
    _to_netscape(cookies, COOKIES_TXT)
    return cookies


def _has_login_cookie(cookies: list) -> bool:
    names = {c.get("name") for c in cookies}
    return bool(names & LOGIN_COOKIE_HINTS)


def login(timeout_sec: int = 180) -> Path:
    """도우인 로그인창을 띄우고, 로그인 완료되면 쿠키 저장.

    사용자가 직접 QR/폰번호로 로그인. 로그인 쿠키 감지되면 자동 저장 후 종료.
    timeout_sec 안에 로그인 안 하면 그냥 현재상태 저장하고 종료.

    반환: cookies.txt 경로 (yt-dlp에 넘길 파일)
    """
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)   # 눈에 보이게
        context = browser.new_context()
        page = context.new_page()
        page.goto(DOUYIN_URL)
        print("[douyin] 브라우저에서 로그인하세요 (QR 또는 폰번호). 로그인 감지되면 자동 저장됩니다...")

        deadline = time.time() + timeout_sec
        logged = False
        while time.time() < deadline:
            try:
                if _has_login_cookie(context.cookies()):
                    logged = True
                    break
            except Exception:
                pass
            page.wait_for_timeout(2000)   # 2초마다 체크

        # 영상 페이지를 한번 방문해 msToken/ttwid 등 다운로드용 전체 쿠키 확보
        try:
            print("[douyin] 영상 페이지 방문해 추가 쿠키(msToken 등) 수집 중...")
            page.goto("https://www.douyin.com/discover", wait_until="networkidle", timeout=20000)
            page.wait_for_timeout(3000)
        except Exception:
            pass

        cookies = _save(context)
        browser.close()
        names = {c.get("name") for c in cookies}
        has_ms = "msToken" in names
        print(f"[douyin] {'로그인 성공' if logged else '타임아웃/비로그인'} | "
              f"쿠키 {len(cookies)}개 | msToken={'O' if has_ms else 'X'} | 저장: {COOKIES_TXT}")
    return COOKIES_TXT


def get_cookiefile() -> str | None:
    """저장된 cookies.txt 경로 반환 (없으면 None)."""
    return str(COOKIES_TXT) if COOKIES_TXT.exists() else None


def is_logged_in() -> bool:
    """저장된 state에 로그인 쿠키가 있는지 (간이 판정)."""
    if not STATE_PATH.exists():
        return False
    try:
        state = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        return _has_login_cookie(state.get("cookies", []))
    except Exception:
        return False


if __name__ == "__main__":
    # python -m app.douyin_auth  → 로그인창 띄우기
    login()
